import { LivresListe } from './livre.type';

export const Livres: LivresListe = [
  {
    id: 1,
    titre: 'Le comte de Monte-Cristo',
    auteur: 'Alexandre Dumas',
    annee: 1846,
    imageLien: 'images/comte-montecristo.jpg',
    prix: 10,
  },
  {
    id: 2,
    titre: 'Fahrenheit 451',
    auteur: 'Ray Bradbury',
    annee: 1953,
    imageLien: 'images/fahrenheit451.jpg',
    prix: 10,
  },
  {
    id: 3,
    titre: 'Fondation',
    auteur: 'Isaac Asimov',
    annee: 1951,
    imageLien: 'images/Fondation.jpg',
    prix: 10,
  },
  {
    id: 4,
    titre: 'Gagner la guerre',
    auteur: 'Jean-Philippe Jaworski',
    annee: 2009,
    imageLien: 'images/gagner-la-guerre.jpg',
    prix: 10,
  },
  {
    id: 5,
    titre: 'Illusions perdues',
    auteur: 'Honoré de Balzac',
    annee: 1837,
    imageLien: 'images/illusions-perdues.jpeg',
    prix: 10,
  },
  {
    id: 6,
    titre: 'Le grand monde',
    auteur: 'Pierre Lemaitre',
    annee: 2022,
    imageLien: 'images/le-grand-monde.webp',
    prix: 10,
  },
  {
    id: 7,
    titre: 'Le portrait de Dorian Gray',
    auteur: 'Oscar Wilde',
    annee: 1890,
    imageLien: 'images/Le-portrait-de-Dorian-Gray.jpg',
    prix: 10,
  },
  {
    id: 8,
    titre: 'Le problème à trois corps',
    auteur: 'Liu Cixin',
    annee: 2006,
    imageLien: 'images/Le-Probleme-a-trois-corps.jpg',
    prix: 10,
  },
  {
    id: 9,
    titre: 'Le seigneur des anneaux',
    auteur: 'J.R.R Tolkien',
    annee: 1954,
    imageLien: 'images/le-seigneur-des-anneaux.jpg',
    prix: 10,
  },
  {
    id: 10,
    titre: 'Les misérables',
    auteur: 'Victor Hugo',
    annee: 1862,
    imageLien: 'images/les-miserables.jpg',
    prix: 10,
  },
  {
    id: 11,
    titre: "L'étranger",
    auteur: 'Albert Camus',
    annee: 1942,
    imageLien: 'images/letranger.jpg',
    prix: 10,
  },
  {
    id: 12,
    titre: "Mémoires d'Hadrien",
    auteur: 'Marguerite Yourcenar',
    annee: 1951,
    imageLien: 'images/memoires-hadrien.jpg',
    prix: 10,
  },
  {
    id: 13,
    titre: 'Neige de printemps',
    auteur: 'Yukio Mishima',
    annee: 1969,
    imageLien: 'images/Neige-de-printemps.jpg',
    prix: 10,
  },
  {
    id: 14,
    titre: 'Les rois maudits',
    auteur: 'Maurice Druon',
    annee: 1955,
    imageLien: 'images/rois-maudits.jpeg',
    prix: 10,
  },
  {
    id: 15,
    titre: 'Vingt Mille Lieues sous les mers',
    auteur: 'Jules Verne',
    annee: 1870,
    imageLien: 'images/vingt-mille-lieues-sous-les-mers.jpg',
    prix: 10,
  },
];
